---
- name: Configurer le NAT dynamique sur le routeur CSR
  hosts: csr1000
  gather_facts: no
  connection: network_cli
  vars:
    acl_number: 10
    wan_interface: GigabitEthernet1
    lan_network: 192.168.103.0
    lan_netmask: 0.0.0.255
  tasks:
    - name: Placer la commande ip nat inside sur les interfaces LAN
      ios_config:
        lines:
          - "interface {{ item }}"
          - "ip nat inside"
        parents: "interface GigabitEthernet"
      loop:
        - GigabitEthernet2
        - GigabitEthernet3
        - GigabitEthernet4
     - name: Placer la commande ip nat outside sur l'interface WAN
       ios_config:
        lines:
          - interface GigabitEthernet1
          - ip nat outside
        parents: interface GigabitEthernet1

     - name: Configurer l'ACL pour autoriser le trafic du réseau LAN
       ios_config:
        lines:
          - "access-list 10 permit 192.168.103.0 255.255.255.0"
      state: present

     - name: Configurer le NAT dynamique avec l'ACL et l'interface WAN
       ios_config:
        lines:
          - "ip nat inside source list 10 interface GigabitEthernet1 overload"

